//# sourceMappingURL=autocomplete.js.map
var EasyAutocomplete=function(c){c.Configuration=function(b){function c(a,e){function b(e,c){for(var f in c)void 0===e[f]&&a.log("Property '"+f+"' does not exist in EasyAutocomplete options API."),"object"===typeof e[f]&&-1===$.inArray(f,m)&&b(e[f],c[f])}b(d,e)}var d={data:"list-required",url:"list-required",dataType:"json",listLocation:function(a){return a},xmlElementName:"",getValue:function(a){return a},autocompleteOff:!0,placeholder:!1,ajaxCallback:function(){},matchResponseProperty:!1,list:{sort:{enabled:!1,
method:function(a,e){a=d.getValue(a);e=d.getValue(e);return a<e?-1:a>e?1:0}},maxNumberOfElements:6,hideOnEmptyPhrase:!0,match:{enabled:!1,caseSensitive:!1,method:function(a,e){return-1<a.search(e)?!0:!1}},showAnimation:{type:"normal",time:400,callback:function(){}},hideAnimation:{type:"normal",time:400,callback:function(){}},onClickEvent:function(){},onSelectItemEvent:function(){},onLoadEvent:function(){},onChooseEvent:function(){},onKeyEnterEvent:function(){},onMouseOverEvent:function(){},onMouseOutEvent:function(){},
onShowListEvent:function(){},onHideListEvent:function(){}},highlightPhrase:!0,theme:"",cssClasses:"",minCharNumber:0,requestDelay:0,adjustWidth:!0,ajaxSettings:{},preparePostData:function(a,e){return a},loggerEnabled:!0,template:"",categoriesAssigned:!1,categories:[{maxNumberOfElements:4}]},m=["ajaxSettings","template"];this.get=function(a){return d[a]};this.equals=function(a,e){var b;b=void 0!==d[a]&&null!==d[a]?!0:!1;return b&&d[a]===e?!0:!1};this.checkDataUrlProperties=function(){return"list-required"===
d.url&&"list-required"===d.data?!1:!0};this.checkRequiredProperties=function(){for(var a in d)if("required"===d[a])return logger.error("Option "+a+" must be defined"),!1;return!0};this.printPropertiesThatDoesntExist=function(a,e){c(a,e)};(function(){"xml"===b.dataType&&(b.getValue||(b.getValue=function(a){return $(a).text()}),b.list||(b.list={}),b.list.sort||(b.list.sort={}),b.list.sort.method=function(a,e){a=b.getValue(a);e=b.getValue(e);return a<e?-1:a>e?1:0},b.list.match||(b.list.match={}),b.list.match.method=
function(a,e){return-1<a.search(e)?!0:!1});if(void 0!==b.categories&&b.categories instanceof Array){for(var a=[],e=0,n=b.categories.length;e<n;e+=1){var c=b.categories[e],g;for(g in d.categories[0])void 0===c[g]&&(c[g]=d.categories[0][g]);a.push(c)}b.categories=a}})();(function(){function a(e,b){var c=e||{},d;for(d in e)void 0!==b[d]&&null!==b[d]&&("object"!==typeof b[d]||b[d]instanceof Array?c[d]=b[d]:a(e[d],b[d]));void 0!==b.data&&null!==b.data&&"object"===typeof b.data&&(c.data=b.data);return c}
d=a(d,b)})();!0===d.loggerEnabled&&c(console,b);d.ajaxSettings=void 0!==b.ajaxSettings&&"object"===typeof b.ajaxSettings?b.ajaxSettings:{};(function(){if("list-required"!==d.url&&"function"!==typeof d.url){var a=d.url;d.url=function(){return a}}void 0!==d.ajaxSettings.url&&"function"!==typeof d.ajaxSettings.url&&(a=d.ajaxSettings.url,d.ajaxSettings.url=function(){return a});if("string"===typeof d.listLocation){var e=d.listLocation;"XML"===d.dataType.toUpperCase()?d.listLocation=function(a){return $(a).find(e)}:
d.listLocation=function(a){return a[e]}}if("string"===typeof d.getValue){var c=d.getValue;d.getValue=function(a){return a[c]}}void 0!==b.categories&&(d.categoriesAssigned=!0)})()};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.Logger=function(){this.error=function(b){console.log("ERROR: "+b)};this.warning=function(b){console.log("WARNING: "+b)}};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.Constans=function(){var b={CONTAINER_CLASS:"easy-autocomplete-container",CONTAINER_ID:"eac-container-",
WRAPPER_CSS_CLASS:"easy-autocomplete"};this.getValue=function(c){return b[c]}};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.ListBuilderService=function(b,c){function d(a,e){function c(){var f={},d;void 0!==a.xmlElementName&&(f.xmlElementName=a.xmlElementName);void 0!==a.listLocation?d=a.listLocation:void 0!==b.get("listLocation")&&(d=b.get("listLocation"));void 0!==d?"string"===typeof d?f.data=$(e).find(d):"function"===typeof d&&(f.data=d(e)):f.data=e;return f}function d(){var b=
{};void 0!==a.listLocation?"string"===typeof a.listLocation?b.data=e[a.listLocation]:"function"===typeof a.listLocation&&(b.data=a.listLocation(e)):b.data=e;return b}var g={},g="XML"===b.get("dataType").toUpperCase()?c():d();void 0!==a.header&&(g.header=a.header);void 0!==a.maxNumberOfElements&&(g.maxNumberOfElements=a.maxNumberOfElements);void 0!==b.get("list").maxNumberOfElements&&(g.maxListSize=b.get("list").maxNumberOfElements);if(void 0!==a.getValue)if("string"===typeof a.getValue){var f=a.getValue;
g.getValue=function(a){return a[f]}}else"function"===typeof a.getValue&&(g.getValue=a.getValue);else g.getValue=b.get("getValue");return g}function m(a){var e=[];void 0===a.xmlElementName&&(a.xmlElementName=b.get("xmlElementName"));$(a.data).find(a.xmlElementName).each(function(){e.push(this)});return e}this.init=function(a){var e=[],c={};c.data=b.get("listLocation")(a);c.getValue=b.get("getValue");c.maxListSize=b.get("list").maxNumberOfElements;e.push(c);return e};this.updateCategories=function(a,
e){if(b.get("categoriesAssigned")){a=[];for(var c=0;c<b.get("categories").length;c+=1){var g=d(b.get("categories")[c],e);a.push(g)}}return a};this.convertXml=function(a){if("XML"===b.get("dataType").toUpperCase())for(var e=0;e<a.length;e+=1)a[e].data=m(a[e]);return a};this.processData=function(a,e){for(var d=0,m=a.length;d<m;d+=1)a[d].data=c(b,a[d],e);return a};this.checkIfDataExists=function(a){for(var b=0,c=a.length;b<c;b+=1)if(void 0!==a[b].data&&a[b].data instanceof Array&&0<a[b].data.length)return!0;
return!1}};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.proccess=function(b,g,d){function m(a,c){b.get("list").match.caseSensitive||("string"===typeof a&&(a=a.toLowerCase()),c=c.toLowerCase());return b.get("list").match.method(a,c)?!0:!1}c.proccess.match=m;var a=g.data,a=function(a,c){var d=[],g;if(b.get("list").match.enabled)for(var f=0,u=a.length;f<u;f+=1)g=b.get("getValue")(a[f]),m(g,c)&&d.push(a[f]);else d=a;return d}(a,d),a=function(a){void 0!==g.maxNumberOfElements&&a.length>
g.maxNumberOfElements&&(a=a.slice(0,g.maxNumberOfElements));return a}(a);return a=function(a){b.get("list").sort.enabled&&a.sort(b.get("list").sort.method);return a}(a)};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.Template=function(b){var c={basic:{type:"basic",method:function(b){return b},cssClass:""},description:{type:"description",fields:{description:"description"},method:function(b){return b+" - description"},cssClass:"eac-description"},iconLeft:{type:"iconLeft",fields:{icon:""},
method:function(b){return b},cssClass:"eac-icon-left"},iconRight:{type:"iconRight",fields:{iconSrc:""},method:function(b){return b},cssClass:"eac-icon-right"},links:{type:"links",fields:{link:""},method:function(b){return b},cssClass:""},custom:{type:"custom",method:function(){},cssClass:""}},d=function(b){var a=b.fields,e;return"description"===b.type?(e=c.description.method,"string"===typeof a.description?e=function(b,c){return b+" - <span>"+c[a.description]+"</span>"}:"function"===typeof a.description&&
(e=function(b,c){return b+" - <span>"+a.description(c)+"</span>"}),e):"iconRight"===b.type?("string"===typeof a.iconSrc?e=function(b,c){return b+"<img class='eac-icon' src='"+c[a.iconSrc]+"' />"}:"function"===typeof a.iconSrc&&(e=function(b,c){return b+"<img class='eac-icon' src='"+a.iconSrc(c)+"' />"}),e):"iconLeft"===b.type?("string"===typeof a.iconSrc?e=function(b,c){return"<img class='eac-icon' src='"+c[a.iconSrc]+"' />"+b}:"function"===typeof a.iconSrc&&(e=function(b,c){return"<img class='eac-icon' src='"+
a.iconSrc(c)+"' />"+b}),e):"links"===b.type?("string"===typeof a.link?e=function(b,c){return"<a href='"+c[a.link]+"' >"+b+"</a>"}:"function"===typeof a.link&&(e=function(b,c){return"<a href='"+a.link(c)+"' >"+b+"</a>"}),e):"custom"===b.type?b.method:c.basic.method};this.getTemplateClass=function(b){var a=function(){return""};return b&&b.type?b.type&&c[b.type]?function(){var a=c[b.type].cssClass;return function(){return a}}():a:a}(b);b=b&&b.type?b.type&&c[b.type]?d(b):c.basic.method:c.basic.method;
this.build=b};return c}(EasyAutocomplete||{}),EasyAutocomplete=function(c){c.main=function(b,g){function d(){function b(a,c){return f.get("highlightPhrase")&&""!==c?(c=c.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),(a+"").replace(new RegExp("("+c+")","gi"),"<b>$1</b>")):a}h.parent().hasClass(r.getValue("WRAPPER_CSS_CLASS"))&&(h.next("."+r.getValue("CONTAINER_CLASS")).remove(),h.unwrap());(function(){var b=$("<div>"),a=r.getValue("WRAPPER_CSS_CLASS");f.get("theme")&&""!==f.get("theme")&&(a+=
" eac-"+f.get("theme"));f.get("cssClasses")&&""!==f.get("cssClasses")&&(a+=" "+f.get("cssClasses"));""!==x.getTemplateClass()&&(a+=" "+x.getTemplateClass());b.addClass(a);h.wrap(b);!0===f.get("adjustWidth")&&(b=h.outerWidth(),h.parent().css("width",b))})();(function(){var a=$("<div>").addClass(r.getValue("CONTAINER_CLASS"));a.attr("id",m()).prepend($("<ul>"));(function(){a.on("show.eac",function(){switch(f.get("list").showAnimation.type){case "slide":var b=f.get("list").showAnimation.time,c=f.get("list").showAnimation.callback;
a.find("ul").slideDown(b,c);break;case "fade":b=f.get("list").showAnimation.time;c=f.get("list").showAnimation.callback;a.find("ul").fadeIn(b);c;break;default:a.find("ul").show()}f.get("list").onShowListEvent()}).on("hide.eac",function(){switch(f.get("list").hideAnimation.type){case "slide":var b=f.get("list").hideAnimation.time,c=f.get("list").hideAnimation.callback;a.find("ul").slideUp(b,c);break;case "fade":b=f.get("list").hideAnimation.time;c=f.get("list").hideAnimation.callback;a.find("ul").fadeOut(b,
c);break;default:a.find("ul").hide()}f.get("list").onHideListEvent()}).on("selectElement.eac",function(){a.find("ul li").removeClass("selected");a.find("ul li").eq(k).addClass("selected");f.get("list").onSelectItemEvent()}).on("loadElements.eac",function(c,e,d){var g="";c=a.find("ul");c.empty().detach();l=[];for(var m=0,q=0,z=e.length;q<z;q+=1){var w=e[q].data;if(0!==w.length){void 0!==e[q].header&&0<e[q].header.length&&c.append("<div class='eac-category' >"+e[q].header+"</div>");for(var n=0,p=w.length;n<
p&&m<e[q].maxListSize;n+=1)g=$("<li><div class='eac-item'></div></li>"),function(){var a=n,c=m,l=e[q].getValue(w[a]);g.find(" > div").on("click",function(){h.val(l).trigger("change");k=c;v(c);f.get("list").onClickEvent();f.get("list").onChooseEvent()}).mouseover(function(){k=c;v(c);f.get("list").onMouseOverEvent()}).mouseout(function(){f.get("list").onMouseOutEvent()}).html(x.build(b(l,d),w[a]))}(),c.append(g),l.push(w[n]),m+=1}}a.append(c);f.get("list").onLoadEvent()})})();h.after(a)})();t=$("#"+
m());f.get("placeholder")&&h.attr("placeholder",f.get("placeholder"))}function m(){var a=h.attr("id");return a=r.getValue("CONTAINER_ID")+a}function a(){A("autocompleteOff",!0)&&h.attr("autocomplete","off");(function(){h.focusout(function(){var a=h.val(),b;f.get("list").match.caseSensitive||(a=a.toLowerCase());for(var c=0,e=l.length;c<e;c+=1)if(b=f.get("getValue")(l[c]),f.get("list").match.caseSensitive||(b=b.toLowerCase()),b===a){k=c;v(k);break}})})();(function(){h.off("keyup").keyup(function(a){function b(a){function c(){var a=
{},b=f.get("ajaxSettings")||{},d;for(d in b)a[d]=b[d];return a}if(!(a.length<f.get("minCharNumber"))){if("list-required"!==f.get("data")){var d=f.get("data"),g=p.init(d),g=p.updateCategories(g,d),g=p.processData(g,a);t.trigger("loadElements.eac",[g,a]);0<h.parent().find("li").length?e():n()}d=c();if(void 0===d.url||""===d.url)d.url=f.get("url");if(void 0===d.dataType||""===d.dataType)d.dataType=f.get("dataType");void 0!==d.url&&"list-required"!==d.url&&(d.url=d.url(a),d.data=f.get("preparePostData")(d.data,
a),$.ajax(d).done(function(b){var c=p.init(b),c=p.updateCategories(c,b),c=p.convertXml(c);if(!1!==f.get("matchResponseProperty")?"string"===typeof f.get("matchResponseProperty")?b[f.get("matchResponseProperty")]===a:"function"===typeof f.get("matchResponseProperty")?f.get("matchResponseProperty")(b)===a:1:1)c=p.processData(c,a),t.trigger("loadElements.eac",[c,a]);p.checkIfDataExists(c)&&0<h.parent().find("li").length?e():n();f.get("ajaxCallback")()}).fail(function(){u.warning("Fail to load response data")}).always(function(){}))}}
switch(a.keyCode){case 27:n();h.trigger("blur");break;case 38:a.preventDefault();0<l.length&&0<k&&(--k,h.val(f.get("getValue")(l[k])),v(k));break;case 40:a.preventDefault();0<l.length&&k<l.length-1&&(k+=1,h.val(f.get("getValue")(l[k])),v(k));break;default:if(40<a.keyCode||8===a.keyCode){var c=h.val();!0!==f.get("list").hideOnEmptyPhrase||8!==a.keyCode||""!==c?0<f.get("requestDelay")?(void 0!==y&&clearTimeout(y),y=setTimeout(function(){b(c)},f.get("requestDelay"))):b(c):n()}}})})();(function(){h.on("keydown",
function(a){a=a||window.event;if(38===a.keyCode)return suppressKeypress=!0,!1}).keydown(function(a){13===a.keyCode&&-1<k&&(h.val(f.get("getValue")(l[k])),f.get("list").onKeyEnterEvent(),f.get("list").onChooseEvent(),k=-1,n(),a.preventDefault())})})();h.off("keypress");(function(){h.focus(function(){""!==h.val()&&0<l.length&&(k=-1,e())})})();(function(){h.blur(function(){setTimeout(function(){k=-1;n()},250)})})()}function e(){t.trigger("show.eac")}function n(){t.trigger("hide.eac")}function v(a){t.trigger("selectElement.eac",
a)}var r=new c.Constans,f=new c.Configuration(g),u=new c.Logger,x=new c.Template(g.template),p=new c.ListBuilderService(f,c.proccess),A=f.equals,h=b,t="",l=[],k=-1,y;c.consts=r;this.getConstants=function(){return r};this.getConfiguration=function(){return f};this.getContainer=function(){return t};this.getSelectedItemIndex=function(){return k};this.getItems=function(){return l};this.getItemData=function(a){return l.length<a||void 0===l[a]?-1:l[a]};this.getSelectedItemData=function(){return this.getItemData(k)};
this.build=function(){d()};this.init=function(){0===h.length?u.error("Input field doesn't exist."):f.checkDataUrlProperties()?f.checkRequiredProperties()?(d(),a()):u.error("Will not work without mentioned properties."):u.error("One of options variables 'data' or 'url' must be defined.")}};c.eacHandles=[];c.getHandle=function(b){return c.eacHandles[b]};c.inputHasId=function(b){return void 0!==$(b).attr("id")&&0<$(b).attr("id").length?!0:!1};c.assignRandomId=function(b){var g;do g="eac-"+Math.floor(1E4*
Math.random());while(0!==$("#"+g).length);elementId=c.consts.getValue("CONTAINER_ID")+g;$(b).attr("id",g)};c.setHandle=function(b,g){c.eacHandles[g]=b};return c}(EasyAutocomplete||{});
(function(c){c.fn.easyAutocomplete=function(b){return this.each(function(){var g=c(this),d=new EasyAutocomplete.main(g,b);EasyAutocomplete.inputHasId(g)||EasyAutocomplete.assignRandomId(g);d.init();EasyAutocomplete.setHandle(d,g.attr("id"))})};c.fn.getSelectedItemIndex=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getSelectedItemIndex():-1};c.fn.getItems=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getItems():-1};c.fn.getItemData=
function(b){var g=c(this).attr("id");return void 0!==g&&-1<b?EasyAutocomplete.getHandle(g).getItemData(b):-1};c.fn.getSelectedItemData=function(){var b=c(this).attr("id");return void 0!==b?EasyAutocomplete.getHandle(b).getSelectedItemData():-1}})(jQuery);